@Webhook = https://localhost:7045

### Create order

POST {{Webhook}}/orders
Content-Type: application/json

{
    "customerName": "aaa",
    "amount": 456
}

### Create subscription

POST {{Webhook}}/webhooks/subscriptions
Content-Type: application/json

{
  "eventType": "order.created",
  "webhookUrl": "https://webhook.site/b68167ed-c2d3-439c-840e-d4795f179c48"
}