@Webhook = http://localhost:54619

### Create order

POST {{Webhook}}/orders
Content-Type: application/json

{
    "customerName": "aaa",
    "amount": 456
}

### Create subscription

POST {{Webhook}}/webhooks/subscriptions
Content-Type: application/json

{
  "eventType": "order.created",
  "webhookUrl": "https://webhook.site/9d5f4460-2010-446e-a11a-7597c8b49cd8"
}